### PR TITLE
refactor: make split task unbatched

### PR DESCRIPTION
**Pull request by fengzixu**
fixes: #96 

1. remove the BatchSplitRequest and BatchSplitResponse
2. change the ExecBatchSplit to the unbatched

### CODE REVIEW

**Comment by fengzixu** [comment]
@Connor1996 Hi. I submitted a PR for the issue #96. 

Actually, for the requirement of `OnReadySplitRegion`, I think we don't need to do any change on it. Maybe I missed some points. 

As I understand, your issue means to change `BatchSplit` with multiple split keys to the `Split` with the only one split key. So I just modify the `ExecBatchSplit`.

**Comment by fengzixu** [comment]
> Thanks for you contribution! Could you help change the `AskBatchSplit` and `MsgSplitRegion` too?

@Connor1996 Sure. I will change it into a new commit

**Comment by Connor1996** [comment]
Please update the proto

**Comment by fengzixu** [comment]
@Connor1996 Have resolved all conflicts.

**Comment by Connor1996** [comment]
seem the test is always falling, please check whether the changes break something?

**Comment by Connor1996** [comment]
any problem now?

**Comment by fengzixu** [comment]
Nop. Just try to resolve the error of unit test. Little busy in recent days. Let me commit by today. @Connor1996

**Pull request merged**
